🔀 :: 커뮤니티 기능 구현
Team-DaeChiWon/Server pull request #8
Opened 2022-09-08 02:07 UTC by yongbin1

커뮤니티 생성 및 조회, 삭제 구현완료되었습니다

2022-09-08 02:23 UTC, ericlee05 requested changes

2022-09-08 02:23 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/repository/CommunityUserRepository.java
> +public interface CommunityUserRepository extends JpaRepository<CommunityUser, Long> {
사용자 조회에는 페이징 기능이 필요해 보이지 않습니다.
`CrudRepository`를 사용해도 문제 없을 거 같아요

2022-09-08 02:30 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/entity/Community.java
> +    @Column(name = "community_explain")
please remove unnecessary code :(

2022-09-08 02:34 UTC, ericlee05 requested changes

2022-09-08 02:34 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/entity/CommunityUser.java
> +public class CommunityUser {
This may cause "the duplication problem" because of omission of unique key :(

2022-09-08 02:34 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/entity/CommunityUser.java
> +public class CommunityUser {
Do you have any logic to prevent this problem?

2022-09-08 02:34 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/entity/CommunityUser.java
> +public class CommunityUser {
I hate this project :(

2022-09-08 02:46 UTC, ericlee05 requested changes

2022-09-08 02:46 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/repository/CommunityUserRepository.java
> +public interface CommunityUserRepository extends CrudRepository<CommunityUser, Long> {
I heard that `CommunityUser` uses persistence cascade from `Community`..
So Why do you use repository even you use persistence cascade?

It's a ridiculous;;
Do not waste your time and memory.. :(

It's like Jindong Huh!

2022-09-09 15:25 UTC, ericlee05 requested changes

2022-09-09 15:25 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/presentation/dto/request/CreateCommunityRequest.java
> +@Getter @AllArgsConstructor
Request dto에는 AllArgsConstructor가 필요 없습니당
@NoArgsConstructor로 기본 생성자만 명시해주셔도 될 거 같아요

2022-09-09 15:25 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/entity/Community.java
> +    private int memberCount;
카페의 회원수는 communityUserList.size() method를 통해서 가져올 수 있습니다
따라서 memberCount는 필요 없을 거 같아여

2022-09-09 15:25 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/service/CommunityService.java
> +                .memberCount(1)
memberCount가 제거되므로 여기도 같이 없애주세요

2022-09-09 15:26 UTC, ericlee05 commented
일해랏 고용빈!

2022-09-09 15:27 UTC, ericlee05 commented
새나라의 개발자 어른이들은 새벽부터 코딩을 한답니다아아

2022-09-09 15:27 UTC, ericlee05 commented
으아 나 피곤해서 맛갔나봐 ㅜ

2022-09-10 05:15 UTC, yongbin1 commented
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-09-10 05:34 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/entity/Community.java
> +    private Long communityIdx;
변수명을 id로 바꿔주시면 좋을 거 같아요

2022-09-10 05:34 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/entity/Community.java
> +    private String communityName;
nullable=false 속성 넣어주세요

2022-09-10 05:34 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/service/CommunityService.java
> +        CommunityUser communityUser = CommunityUser.builder()
Owner 유저를 커뮤니티에 추가하는 로직은 별도의 메서드를 만드는게 좋을 거 같아요.
그러면 일반 유저가 커뮤니티 가입할때도 그 로직을 쓸 수 있을듯 하네요

2022-09-10 05:34 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/service/CommunityService.java
> +        community.getCommunityUserList().remove(communityUser);
`orphanRemoval=true` 쓰신걸로 아는데, 그냥 owner 측에서 커뮤니티를 삭제시키면 고아 객체로 취급되서 해결될 거 같아요

2022-09-10 05:35 UTC, ericlee05 commented
우리 Entity랑 DTO 변환할 때 Builder로 직접 만들지 말고 ModelMapper써도 괜찮을 거 같은데 어케 생각하시져

http://modelmapper.org/

2022-09-10 06:31 UTC, yongbin1 commented
시간이 얼마남지 않아 본선 올라간다면 변경하는게 어떤가요??

2022-09-10 06:37 UTC, yongbin1 commented on src/main/java/com/project/daechiwon/domain/community/service/CommunityService.java
> +        CommunityUser communityUser = CommunityUser.builder()
Owner 유저는 카페 설립자인데 별도의 메서드를 만들더라도 일반 유저가 커뮤니티를 가입할때는 사용이 되지 않을 것 같은데 맞나요??

2022-09-10 13:10 UTC, ericlee05 commented
그렇게 하져

2022-09-10 13:11 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/community/service/CommunityService.java
> +        CommunityUser communityUser = CommunityUser.builder()
음 제가 말을 잘못했네요

User를 커뮤니티에 등록해주는 메서드를 만들고, 그 메서드를 이 로직에서 호출한다면 code duplication을 막을 수 있을 거 같아서요

2022-09-11 10:42 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/user/entity/User.java
> +    private List<Community> communityList;
이거 지워주시고

2022-09-11 10:42 UTC, ericlee05 commented on src/main/java/com/project/daechiwon/domain/user/entity/User.java
> +    private List<CommunityUser> communityUserList;
```java
public List<Community> getCommunityList() {
    return getCommunityUserList().stream()
        .map(it -> Communtiy.builder()
            .builder 코드 여기에..
            .build()
        )
        .collect(Collectors.toList())
}
```

이렇게 추가하시면 되지 않을까요

2022-09-14 12:36 UTC, qkrthdud002 approved these changes

2022-09-14 23:57 UTC, merged